spring.application.name=OnlineShop

project.image.path=images/

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:a2975bca-9c9c-4216-90ee-cb0f59bee307

#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=parola123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=parola123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/your_db
#spring.datasource.username=your_user
#spring.datasource.password=your_password

# Groq API Key (free) - get yours at https://console.groq.com
groq.api.key=<key>

spring.app.jwtSecret=OnlineShopSuperSecretJwtKey2026abSecureEnough256bits
spring.app.jwtExpirationMs=30000000000
spring.app.jwtcookie = springBootecom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.platforma.onlineshop=DEBUG

image.base.url=http://localhost:8080/images

#Stripe key
stripe.secret.key=${STRIPE_SECRET_KEY}